server:
  port: 6002

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: usersDB
  application:
    name: USER-SERVICE
  mvc:
    pathMatch:
      matching-strategy: ANT_PATH_MATCHER

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  service_url:
    default:zone: http://localhost:8761
  instance:
    hostname: localhost
