server:
  port: 6005

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: adminDB
  application:
    name: ADMIN-SERVICE
  mvc:
    pathMatch:
      matching-strategy: ANT_PATH_MATCHER

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service_url:
      default:zone: http://localhost:8761/eureka
    instance:
      hostname: localhost
